#!/bin/bash

# Title and Header
echo -e "\e[1;36m  _____                   __     __  __             __  _     \e[0m"
echo -e "\e[1;36m / ___/__ ___ _________ _/ /    / / / /__  _______ / /_(_)   \e[0m"
echo -e "\e[1;36m/ (_ / _ \`/ // / __/ _ \`/ _ \\  / /_/ / _ \\/ __/ -_) __/ /   \e[0m"
echo -e "\e[1;36m\\___/\\_,_/\\_,_/_/  \\_,_/_.__/  \\____/ .__/_/  \\__/\\__/_/    \e[0m"
echo -e "\e[1;36m                                   /_/                    \e[0m"

echo -e "\e[1;34m┌───────────────────────────────────────────────────────────┐\e[0m"
echo -e "\e[1;34m│                     Gaurab Upreti                         │\e[0m"
echo -e "\e[1;34m│               Software Engineer, DevOps                   │\e[0m"
echo -e "\e[1;34m└───────────────────────────────────────────────────────────┘\e[0m\n"

# Professional Experience
echo -e "\e[1;33mProfessional Experience\e[0m"
echo -e "\e[1;32m──────────────────────────────────────────────────────────────\e[0m"

echo -e "\e[1;36m┌ LEAPFROG TECHNOLOGY, INC. ──────────────────────────────────\e[0m"
echo -e "\e[1;36m│ Software Engineer, DevOps │ Feb 2024 – Present             │\e[0m"
echo -e "├─────────────────────────────────────────────────────────────┤"
echo -e "│ • Designed scalable AWS infra using Terraform with          │"
echo -e "│   reusable modules for multi-environment deployments.       │"
echo -e "│ • Deployed containerized workloads on Kubernetes, ECS,      │"
echo -e "│   and Docker Swarm with HA and auto-scaling.                │"
echo -e "│ • Built CI/CD pipelines (GitHub Actions, Bitbucket          │"
echo -e "│   Pipelines, Jenkins) for fast, reliable releases.          │"
echo -e "│ • Implemented GitOps for version-controlled, auditable      │"
echo -e "│   infrastructure and automated provisioning.                │"
echo -e "│ • Engineered HA systems with auto-scaling, health checks,   │"
echo -e "│   and rollback mechanisms for reliability.                  │"
echo -e "│ • Strengthened security via IAM least privilege, network     │"
echo -e "│   controls, encryption, and secrets management.             │"
echo -e "│ • Supported compliance/audit readiness with structured      │"
echo -e "│   logging, access controls, and tagging strategies.         │"
echo -e "│ • Implemented observability with ELK Stack, Prometheus,     │"
echo -e "│   Grafana, and Zabbix for monitoring and alerting.          │"
echo -e "│ • Led incident troubleshooting and root cause analysis.     │"
echo -e "│ • Optimized AWS costs via usage analysis, right-sizing,     │"
echo -e "│   and tag-based cost allocation.                            │"
echo -e "│ • Built internal tools: AWS cost dashboard and AD user      │"
echo -e "│   management system.                                        │"
echo -e "│ • Managed multi-account AWS with Organizations and SSO.     │"
echo -e "│ • Supported AI/ML infra including deployment, monitoring,   │"
echo -e "│   and cost optimization of GenAI applications.              │"
echo -e "│ • Built a RAG-based GenAI solution to analyze CloudWatch    │"
echo -e "│   logs and generate operational insights.                   │"
echo -e "│ • Worked with AWS Bedrock and SageMaker for model           │"
echo -e "│   inference and ML lifecycle workflows.                     │"
echo -e "│ • Deployed AI apps on Azure using Azure AI services.        │"
echo -e "│ • Collaborated with teams to improve deployment workflows   │"
echo -e "│   and production readiness.                                 │"
echo -e "└─────────────────────────────────────────────────────────────┘"

echo -e "\e[1;36m┌ NAXA ───────────────────────────────────────────────────────\e[0m"
echo -e "\e[1;36m│ DevOps Intern │ Sep 2023 – Dec 2023                        │\e[0m"
echo -e "├─────────────────────────────────────────────────────────────┤"
echo -e "│ • Created CI/CD pipelines using GitHub Actions and Jenkins  │"
echo -e "│   for multi-service applications.                           │"
echo -e "│ • Built Docker images and containerized backend + frontend  │"
echo -e "│   applications.                                             │"
echo -e "│ • Used Nginx for reverse proxying and load balancing.       │"
echo -e "│ • Managed DNS configurations using Cloudflare.              │"
echo -e "│ • Ran Linux server operations and performed server-level    │"
echo -e "│   troubleshooting.                                          │"
echo -e "└─────────────────────────────────────────────────────────────┘\n"

# Skills
echo -e "\e[1;33mSkills\e[0m"
echo -e "\e[1;32m──────────────────────────────────────────────────────────────\e[0m"
echo -e "• \e[1;35mLanguage\e[0m                    : Python"
echo -e "• \e[1;35mDatabase & Caching\e[0m          : PostgreSQL, Redis"
echo -e "• \e[1;35mContainers & Orchestration\e[0m  : Docker, Kubernetes"
echo -e "• \e[1;35mCloud - AWS\e[0m                 : EC2, VPC, IAM, RDS, S3, ECS,"
echo -e "                                Lambda, SageMaker, Bedrock"
echo -e "• \e[1;35mCloud - Azure\e[0m               : VM, App Service, Blob, VNets"
echo -e "• \e[1;35mIaC & Automation\e[0m            : Terraform, CloudFormation,"
echo -e "                                Ansible, Packer, Bash"
echo -e "• \e[1;35mCI/CD & GitOps\e[0m              : GitHub Actions, Bitbucket"
echo -e "                                Pipelines, Jenkins, GitOps"
echo -e "• \e[1;35mMonitoring & Logging\e[0m        : CloudWatch, Prometheus,"
echo -e "                                Grafana, Zabbix"
echo -e "• \e[1;35mSecurity & Compliance\e[0m       : IAM least-privilege, encryption"
echo -e "                                (at rest & in transit), secrets"
echo -e "                                mgmt, audit logging, PCI-DSS"
echo -e "                                and SOC 2 awareness\n"

# Education
echo -e "\e[1;33mEducation\e[0m"
echo -e "\e[1;32m──────────────────────────────────────────────────────────────\e[0m"
echo -e "\e[1;35mBachelor in Information Technology\e[0m"
echo -e "Texas College of Mgmt. & IT, Lincoln University (2019 – 2023)\n"

# Certifications
echo -e "\e[1;33mCertifications\e[0m"
echo -e "\e[1;32m──────────────────────────────────────────────────────────────\e[0m"
echo -e "• \e[1;36m☁ \e[0m AWS Certified Solutions Architect - Associate (SAA-C03)"
echo -e "• \e[1;36m☁ \e[0m AWS Certified Cloud Practitioner (CLF-C02)"
echo -e "• \e[1;34m⬡ \e[0m Microsoft Azure Fundamentals (AZ-900)\n"
